### PR TITLE
feat: Adds publishConfig to gh packages

### LINKED ISSUE #1: No packages are created
https://github.com/features/packages

GH supports packages, do whatever it needed to get this into the npm.pkg.github.com package registry.

### PR DESCRIPTION
**Pull request by Gerlison**
Fixes #1 

For publishing:
1. login to npm cli
2. run: npm publish

### CODE REVIEW

**Comment by jrwren** [comment]
`npm login --registry=https://npm.pkg.github.com ` should work, but i have 2 factor setup for github.

Need to use a personal access token instead of a password: https://docs.github.com/en/free-pro-team@latest/github/authenticating-to-github/creating-a-personal-access-token

When I run npm publish:

```
npm notice 
npm notice 📦  petname@1.0.0
npm notice === Tarball Contents === 
npm notice 17.9kB index.js           
npm notice 17.9kB petname.js         
npm notice 230B   run.js             
npm notice 537B   package.json       
npm notice 208B   README.md          
npm notice 242B   update-wordlists.sh
npm notice 915B   index.js.tmpl      
npm notice === Tarball Details === 
npm notice name:          petname                                 
npm notice version:       1.0.0                                   
npm notice package size:  6.1 kB                                  
npm notice unpacked size: 37.9 kB                                 
npm notice shasum:        7cf798961492f6abf8616ec71272a0bc10256c8c
npm notice integrity:     sha512-WEtR6tIkHE2gR[...]57oJMqk9oRE2w==
npm notice total files:   7                                       
npm notice 
npm ERR! code E404
npm ERR! 404 Not Found - PUT https://npm.pkg.github.com/petname
npm ERR! 404 
npm ERR! 404  'petname@1.0.0' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/jrwren/.npm/_logs/2020-10-03T18_27_23_911Z-debug.log
```
  I don't know what to do.

**Comment by jrwren** [comment]
I did some research. The name of hte package must include the github user:

```
-  "name": "petname",
+  "name": "@jrwren/petname",
```

**Comment by Gerlison** [comment]
> I did some research. The name of hte package must include the github user:
> 
> ```
> -  "name": "petname",
> +  "name": "@jrwren/petname",
> ```

I forgot that, sorry. Did you get the solution already? I can commit it and open another PR.

**Comment by jrwren** [comment]
I got it.

**Pull request merged**
